version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: keygen_ce
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "10000:10000"
    depends_on:
      - db

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db

  setup:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db

  init:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    command: ["./keygen-init"]

volumes:
  db_data:
